language: php
php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4snapshot'
matrix:
    include:
        - php: '5.4'
          dist: trusty
        - php: '5.5'
          dist: trusty
before_script:
    - git clone --depth=50 https://github.com/ezyang/simpletest.git
    - cp test-settings.travis.php test-settings.php
script:
    - php tests/index.php
